name: RobertChong
favicon: null
layout_spectrum: 0.7347549123223871
typography_spectrum: 0.08624489861540496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.11729415855370462
  lightness: 0.06418559327721596
  saturation: 0.765832485165447
  rhythmicContrast: 0.9082245174795389
purpose: []
